# frozen_string_literal: true

module CourseSubjects
  ANCIENT_HEBREW = "Ancient Hebrew"
  APPLIED_BIOLOGY = "applied biology"
  APPLIED_CHEMISTRY = "applied chemistry"
  APPLIED_COMPUTING = "applied computing"
  APPLIED_PHYSICS = "applied physics"
  ARABIC_LANGUAGES = "Arabic languages"
  ART_AND_DESIGN = "art and design"
  BIOLOGY = "biology"
  BUSINESS_MANAGEMENT = "business and management"
  BUSINESS_STUDIES = "business studies"
  CHEMISTRY = "chemistry"
  CHILD_DEVELOPMENT = "child development"
  CHINESE_LANGUAGES = "Chinese languages"
  CITIZENSHIP = "Citizenship"
  CLASSICAL_GREEK_STUDIES = "classical Greek studies"
  CLASSICAL_STUDIES = "classical studies"
  COMPUTER_SCIENCE = "computer science"
  CONSTRUCTION_AND_THE_BUILT_ENVIRONMENT = "construction and the built environment"
  DANCE = "dance"
  DESIGN = "design"
  DESIGN_AND_TECHNOLOGY = "Design and technology"
  DRAMA = "drama"
  EARLY_YEARS_TEACHING = "early years teaching"
  ECONOMICS = "economics"
  ENGLISH_AS_SECOND_LANGUAGE = "English as a second or other language"
  ENGLISH_STUDIES = "English studies"
  ENVIRONMENTAL_SCIENCES = "environmental sciences"
  FOOD_AND_BEVERAGE_STUDIES = "food and beverage studies"
  FRENCH_LANGUAGE = "French language"
  GENERAL_OR_INTEGRATED_ENGINEERING = "general or integrated engineering"
  GENERAL_SCIENCES = "general sciences"
  GEOGRAPHY = "geography"
  GERMAN_LANGUAGE = "German language"
  GRAPHIC_DESIGN = "graphic design"
  HAIR_AND_BEAUTY_SCIENCES = "hair and beauty sciences"
  HEALTH_AND_SOCIAL_CARE = "health and social care"
  HEALTH_STUDIES = "health studies"
  HISTORICAL_LINGUISTICS = "historical linguistics"
  HISTORY = "history"
  HOSPITALITY = "hospitality"
  INFORMATION_TECHNOLOGY = "information technology"
  ITALIAN_LANGUAGE = "Italian language"
  JAPANESE_LANGUAGE = "Japanese language"
  LATIN_LANGUAGE = "Latin language"
  LAW = "law"
  MANUFACTURING_ENGINEERING = "manufacturing engineering"
  MATERIALS_SCIENCE = "materials science"
  MATHEMATICS = "mathematics"
  MEDIA_AND_COMMUNICATION_STUDIES = "media and communication studies"
  MODERN_LANGUAGES = "modern languages"
  MUSIC_EDUCATION_AND_TEACHING = "music education and teaching"
  PERFORMING_ARTS = "performing arts"
  PHILOSOPHY = "philosophy"
  PHYSICAL_EDUCATION = "Physical education"
  PHYSICS = "physics"
  PORTUGUESE_LANGUAGE = "Portuguese language"
  PRIMARY_TEACHING = "primary teaching"
  PRODUCTION_AND_MANUFACTURING_ENGINEERING = "production and manufacturing engineering"
  PRODUCT_DESIGN = "product design"
  PSYCHOLOGY = "psychology"
  PUBLIC_SERVICES = "public services"
  RECREATION_AND_LEISURE_STUDIES = "recreation and leisure studies"
  RELIGIOUS_STUDIES = "religious studies"
  RETAIL_MANAGEMENT = "retail management"
  RUSSIAN_LANGUAGES = "Russian languages"
  SCIENCE = "science"
  SOCIAL_SCIENCES = "social sciences"
  SPANISH_LANGUAGE = "Spanish language"
  SPECIALIST_TEACHING_PRIMARY_WITH_MATHEMETICS = "specialist teaching (primary with mathematics)"
  SPORTS_MANAGEMENT = "sports management"
  SPORT_AND_EXERCISE_SCIENCES = "sport and exercise sciences"
  STATISTICS = "statistics"
  TEXTILES_TECHNOLOGY = "textiles technology"
  TRAVEL_AND_TOURISM = "travel and tourism"
  UK_GOVERNMENT_PARLIAMENTARY_STUDIES = "UK government / Parliamentary studies"
  WELSH_LANGUAGE = "Welsh language"

  MAPPING = {
    ANCIENT_HEBREW => ::DegreeSubjects::ANCIENT_HEBREW_LANGUAGE,
    APPLIED_BIOLOGY => ::DegreeSubjects::APPLIED_BIOLOGY,
    APPLIED_CHEMISTRY => ::DegreeSubjects::APPLIED_CHEMISTRY,
    APPLIED_COMPUTING => ::DegreeSubjects::APPLIED_COMPUTING,
    APPLIED_PHYSICS => ::DegreeSubjects::APPLIED_PHYSICS,
    ARABIC_LANGUAGES => ::DegreeSubjects::ARABIC_LANGUAGES,
    ART_AND_DESIGN => ::DegreeSubjects::CREATIVE_ARTS_AND_DESIGN,
    BIOLOGY => ::DegreeSubjects::BIOLOGY,
    BUSINESS_MANAGEMENT => ::DegreeSubjects::BUSINESS_AND_MANAGEMENT,
    BUSINESS_STUDIES => ::DegreeSubjects::BUSINESS_STUDIES,
    CHEMISTRY => ::DegreeSubjects::CHEMISTRY,
    CHILD_DEVELOPMENT => ::DegreeSubjects::CHILDHOOD_STUDIES,
    CHINESE_LANGUAGES => ::DegreeSubjects::CHINESE_LANGUAGES,
    CITIZENSHIP => nil,
    CLASSICAL_GREEK_STUDIES => ::DegreeSubjects::CLASSICAL_GREEK_STUDIES,
    CLASSICAL_STUDIES => ::DegreeSubjects::CLASSICAL_STUDIES,
    COMPUTER_SCIENCE => ::DegreeSubjects::COMPUTER_SCIENCE,
    CONSTRUCTION_AND_THE_BUILT_ENVIRONMENT => ::DegreeSubjects::CONSTRUCTION_AND_THE_BUILT_ENVIRONMENT,
    DANCE => ::DegreeSubjects::DANCE,
    DESIGN => ::DegreeSubjects::DESIGN,
    DESIGN_AND_TECHNOLOGY => nil,
    DRAMA => ::DegreeSubjects::DRAMA,
    EARLY_YEARS_TEACHING => ::DegreeSubjects::EARLY_YEARS_TEACHING,
    ECONOMICS => ::DegreeSubjects::ECONOMICS,
    ENGLISH_AS_SECOND_LANGUAGE => ::DegreeSubjects::ENGLISH_AS_A_SECOND_LANGUAGE,
    ENGLISH_STUDIES => ::DegreeSubjects::ENGLISH_STUDIES,
    ENVIRONMENTAL_SCIENCES => ::DegreeSubjects::ENVIRONMENTAL_SCIENCES,
    FOOD_AND_BEVERAGE_STUDIES => ::DegreeSubjects::FOOD_AND_BEVERAGE_STUDIES,
    FRENCH_LANGUAGE => ::DegreeSubjects::FRENCH_LANGUAGE,
    GENERAL_OR_INTEGRATED_ENGINEERING => ::DegreeSubjects::GENERAL_OR_INTEGRATED_ENGINEERING,
    GENERAL_SCIENCES => ::DegreeSubjects::GENERAL_SCIENCE,
    GEOGRAPHY => ::DegreeSubjects::GEOGRAPHY,
    GERMAN_LANGUAGE => ::DegreeSubjects::GERMAN_LANGUAGE,
    GRAPHIC_DESIGN => ::DegreeSubjects::GRAPHIC_DESIGN,
    HAIR_AND_BEAUTY_SCIENCES => ::DegreeSubjects::HAIR_AND_BEAUTY_SCIENCES,
    HEALTH_AND_SOCIAL_CARE => ::DegreeSubjects::HEALTH_AND_SOCIAL_CARE,
    HEALTH_STUDIES => ::DegreeSubjects::HEALTH_STUDIES,
    HISTORICAL_LINGUISTICS => ::DegreeSubjects::HISTORICAL_LINGUISTICS,
    HISTORY => ::DegreeSubjects::HISTORY,
    HOSPITALITY => ::DegreeSubjects::HOSPITALITY,
    INFORMATION_TECHNOLOGY => ::DegreeSubjects::INFORMATION_TECHNOLOGY,
    ITALIAN_LANGUAGE => ::DegreeSubjects::ITALIAN_LANGUAGE,
    JAPANESE_LANGUAGE => ::DegreeSubjects::JAPANESE_LANGUAGES,
    LATIN_LANGUAGE => ::DegreeSubjects::LATIN_LANGUAGE,
    LAW => ::DegreeSubjects::LAW,
    MANUFACTURING_ENGINEERING => ::DegreeSubjects::MANUFACTURING_ENGINEERING,
    MATERIALS_SCIENCE => ::DegreeSubjects::MATERIALS_SCIENCE,
    MATHEMATICS => ::DegreeSubjects::MATHEMATICS,
    MEDIA_AND_COMMUNICATION_STUDIES => ::DegreeSubjects::MEDIA_AND_COMMUNICATION_STUDIES,
    MODERN_LANGUAGES => ::DegreeSubjects::MODERN_LANGUAGES,
    MUSIC_EDUCATION_AND_TEACHING => ::DegreeSubjects::MUSIC_EDUCATION_AND_TEACHING,
    PERFORMING_ARTS => ::DegreeSubjects::PERFORMING_ARTS,
    PHILOSOPHY => ::DegreeSubjects::PHILOSOPHY,
    PHYSICAL_EDUCATION => nil,
    PHYSICS => ::DegreeSubjects::PHYSICS,
    PORTUGUESE_LANGUAGE => ::DegreeSubjects::PORTUGUESE_LANGUAGE,
    PRIMARY_TEACHING => ::DegreeSubjects::PRIMARY_TEACHING,
    PRODUCTION_AND_MANUFACTURING_ENGINEERING => ::DegreeSubjects::PRODUCTION_AND_MANUFACTURING_ENGINEERING,
    PRODUCT_DESIGN => ::DegreeSubjects::PRODUCT_DESIGN,
    PSYCHOLOGY => ::DegreeSubjects::PSYCHOLOGY,
    PUBLIC_SERVICES => ::DegreeSubjects::PUBLIC_SERVICES,
    RECREATION_AND_LEISURE_STUDIES => ::DegreeSubjects::RECREATION_AND_LEISURE_STUDIES,
    RELIGIOUS_STUDIES => ::DegreeSubjects::RELIGIOUS_STUDIES,
    RETAIL_MANAGEMENT => ::DegreeSubjects::RETAIL_MANAGEMENT,
    RUSSIAN_LANGUAGES => ::DegreeSubjects::RUSSIAN_LANGUAGES,
    SOCIAL_SCIENCES => ::DegreeSubjects::SOCIAL_SCIENCES,
    SPANISH_LANGUAGE => ::DegreeSubjects::SPANISH_LANGUAGE,
    SPECIALIST_TEACHING_PRIMARY_WITH_MATHEMETICS => ::DegreeSubjects::SPECIALIST_TEACHING,
    SPORTS_MANAGEMENT => ::DegreeSubjects::SPORTS_MANAGEMENT,
    SPORT_AND_EXERCISE_SCIENCES => ::DegreeSubjects::SPORT_AND_EXERCISE_SCIENCES,
    STATISTICS => ::DegreeSubjects::STATISTICS,
    TEXTILES_TECHNOLOGY => ::DegreeSubjects::TEXTILES_TECHNOLOGY,
    TRAVEL_AND_TOURISM => ::DegreeSubjects::TRAVEL_AND_TOURISM,
    UK_GOVERNMENT_PARLIAMENTARY_STUDIES => ::DegreeSubjects::UK_GOVERNMENT_PARLIAMENTARY_STUDIES,
    WELSH_LANGUAGE => ::DegreeSubjects::WELSH_LANGUAGE,
  }.freeze
end
