require:
  - ./lib/rubocop/cop/govuk/govuk_button_to.rb
  - ./lib/rubocop/cop/govuk/govuk_link_to.rb
  - ./lib/rubocop/cop/govuk/govuk_submit.rb
  - ./lib/rubocop/cop/register/register_form_with.rb
  - rubocop-capybara

plugins:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_from:
  - ./config/rubocop/layout.yml
  - ./config/rubocop/lint.yml
  - ./config/rubocop/metrics.yml
  - ./config/rubocop/naming.yml
  - ./config/rubocop/rails.yml
  - ./config/rubocop/style.yml
  - ./config/rubocop/rspec.yml
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/data_schema.rb"
    - "node_modules/**/*"

Style/MethodCallWithArgsParentheses:
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInStringInterpolation: true
  AllowParenthesesInChaining: true
  Enabled: true
  Exclude:
    - "spec/**/*"
    - "db/data/*"
    - "db/migrate/*"
    - "config/routes/*"

Style/HashSyntax:
  EnforcedShorthandSyntax: consistent

Style/SafeNavigationChainLength:
  Max: 3

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

# These can't be moved into their own config files. erb_lint won't find them unless the require is
# in the same file with them. If we do that the path becomes ../../lib etc. Rubocop can resolve this fine
# but erb_lint can't so one or other of them doesn't work.

Govuk:
  Include:
    - "app/views/**/*"
    - "app/components/**/*"
  Exclude:
    - "app/components/trainees/confirmation/degrees/view.html.erb"
    - "app/components/personas/view.html.erb"

Govuk/GovukLinkTo:
  Exclude:
    - "app/components/govuk_button_link_to/view.rb"

Govuk/GovukSubmit:
  Exclude:
    - "app/components/confirmation/degrees/view.html.erb"
    - "app/components/personas/view.html.erb"

Register/RegisterFormWith:
  Include:
    - "app/views/**/*"
    - "app/components/**/*"

Style/OpenStructUse:
  Exclude:
    - "config/initializers/**/*"
    - "db/data/**/*"
    - "spec/**/*"

Rails/UnknownEnv:
  Environments:
    - productiondata
    - sandbox
    - production
    - development
    - test

Metrics/CollectionLiteralLength:
  Exclude:
    - "app/lib/code_sets/**/*"
    - "app/lib/hesa/**/*"
    - "config/initializers/subjects/**/*"
    - "db/data/**/*"

Rails/FindEach:
  Exclude:
    - "spec/services/trainees/create_from_apply_spec.rb"
    - "db/data/20230612133512_backfill_disability_uuids_from_dfe_reference_gem.rb"

Rails/RedundantActiveRecordAllMethod:
  Exclude:
    - "spec/models/service_update_spec.rb"
    - "spec/lib/dqt/params/update_spec.rb"
    - "app/lib/dfe_reference/degrees_query.rb"
    - "app/services/degrees/fix_to_match_reference_data.rb"
    - "spec/factories/degrees.rb"
    - "spec/lib/dfe_reference/degrees_query_spec.rb"
    - "spec/lib/dqt/params/trn_request_spec.rb"
    - "spec/lib/dqt/params/update_spec.rb"
    - "spec/models/degree_spec.rb"

Rails/FilePath:
  Exclude:
    - "spec/data_migrations/**/*"
    - "spec/models/api/**/*"
    - "spec/services/api/**/*"
    - "spec/requests/api/**/*"
    - "spec/serializers/api/**/*"

RSpec/SpecFilePathFormat:
  Exclude:
    - "spec/data_migrations/**/*"
    - "spec/models/api/**/*"
    - "spec/services/api/**/*"
    - "spec/requests/api/**/*"
    - "spec/serializers/api/**/*"

Capybara/NegationMatcher:
  EnforcedStyle: not_to
