require:
  - ./lib/rubocop/cop/govuk/govuk_button_to.rb
  - ./lib/rubocop/cop/govuk/govuk_link_to.rb
  - ./lib/rubocop/cop/govuk/govuk_submit.rb
  - ./lib/rubocop/cop/register/register_form_with.rb

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_from:
  - ./config/rubocop/layout.yml
  - ./config/rubocop/lint.yml
  - ./config/rubocop/metrics.yml
  - ./config/rubocop/naming.yml
  - ./config/rubocop/rails.yml
  - ./config/rubocop/style.yml
  - ./config/rubocop/rspec.yml
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/data_schema.rb"
    - "node_modules/**/*"

Style/MethodCallWithArgsParentheses:
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInStringInterpolation: true
  AllowParenthesesInChaining: true
  Enabled: true
  Exclude:
    - "spec/**/*"
    - "db/data/*"
    - "db/migrate/*"
    - "config/routes/*"

Style/HashSyntax:
  EnforcedShorthandSyntax: consistent

Style/SafeNavigationChainLength:
  Max: 3

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Naming/PredicateMethod:
  Exclude:
    - "app/controllers/trainees/check_details_controller.rb"
    - "app/controllers/trainees/hesa/enable_edits_controller.rb"
    - "app/controllers/trainees/placement_school_searches_controller.rb"
    - "app/controllers/trainees/placements/confirm_details_controller.rb"
    - "app/controllers/trainees/placements_controller.rb"
    - "app/forms/bulk_update/bulk_add_trainees_import_rows_form.rb"
    - "app/forms/bulk_update/placements_form.rb"
    - "app/forms/degree_form.rb"
    - "app/forms/diversities/disability_detail_form.rb"
    - "app/forms/placement_form.rb"
    - "app/models/reports/trainee_report.rb"
    - "app/services/api/trainees/withdraw_response.rb"
    - "app/services/bulk_update/add_trainees/validate_file.rb"
    - "app/services/concerns/cacheable.rb"
    - "app/validators/date_relative_to_time_validator.rb"
    - "spec/support/current_academic_cycle.rb"

# These can't be moved into their own config files. erb_lint won't find them unless the require is
# in the same file with them. If we do that the path becomes ../../lib etc. Rubocop can resolve this fine
# but erb_lint can't so one or other of them doesn't work.

Govuk:
  Include:
    - "app/views/**/*"
    - "app/components/**/*"
  Exclude:
    - "app/components/trainees/confirmation/degrees/view.html.erb"
    - "app/components/personas/view.html.erb"

Govuk/GovukLinkTo:
  Exclude:
    - "app/components/govuk_button_link_to/view.rb"

Govuk/GovukSubmit:
  Exclude:
    - "app/components/confirmation/degrees/view.html.erb"
    - "app/components/personas/view.html.erb"

Register/RegisterFormWith:
  Include:
    - "app/views/**/*"
    - "app/components/**/*"

Style/OpenStructUse:
  Exclude:
    - "config/initializers/**/*"
    - "db/data/**/*"
    - "spec/**/*"

Metrics/CollectionLiteralLength:
  Exclude:
    - "app/lib/code_sets/**/*"
    - "app/lib/hesa/**/*"
    - "config/initializers/subjects/**/*"
    - "db/data/**/*"

RSpec/SpecFilePathFormat:
  Exclude:
    - "spec/data_migrations/**/*"
    - "spec/models/api/**/*"
    - "spec/services/api/**/*"
    - "spec/services/bulk_update/add_trainees/**/*"
    - "spec/forms/bulk_update/v20*/**/*"
    - "spec/models/reports/v20*/**/*"
    - "spec/requests/api/**/*"
    - "spec/serializers/api/**/*"

Capybara/NegationMatcher:
  EnforcedStyle: not_to
