ignore:
  - "app/lib/custom_log_formatter.rb"
  - "lib/tasks/api.rake"
  - "lib/tasks/auto_generate_diagram.rake"
  - "lib/tasks/backfill_hesa.rake"
  - "lib/tasks/copy_providers_to_lead_partners.rake"
  - "lib/tasks/country_autocomplete_graph.rake"
  - "lib/tasks/diversity.rake"
  - "lib/tasks/example_data.rake"
  - "lib/tasks/fix_invalid_degrees.rake"
  - "lib/tasks/funding.rake"
  - "lib/tasks/generate_test_trainee_csv.rake"
  - "lib/tasks/govuk_lint.rake"
  - "lib/tasks/import_hesa_placements.rake"
  - "lib/tasks/migrate_swallowing_concurrent_migration_exceptions.rake"
  - "lib/tasks/publish_provider_check.rake"
  - "lib/tasks/recalculate_academic_cycles.rake"
  - "lib/tasks/remove_duplicates.rake"
  - "lib/tasks/trainees_create_from_csv.rake"
  - "lib/tasks/trainees_hpitt_bulk_submit.rake"
  - ".github"
