name: bring-docker-image-up
description: Bring docker image up

inputs:
  docker-image:
    required: true
  image-tag:
    required: true

runs:
  using: composite
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "IMAGE_TAG=${{ inputs.image-tag }}" >> $GITHUB_ENV

    - name: Pull docker image
      shell: bash
      run: docker pull ${{ inputs.docker-image }}:${{ inputs.image-tag }}

    - name: Bring image up
      shell: bash
      run: |
        docker compose up --no-build -d
        docker compose exec -T web /bin/sh -c "./wait-for-command.sh -c 'nc -z db 5432' -s 0 -t 20"
      env:
        SENTRY_DSN: dummy
