name: bring-docker-image-up
description: Bring docker image up

inputs:
  azure-credentials:
    required: true
  docker-image:
    required: true
  image-tag:
    required: true

runs:
  using: composite
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "IMAGE_TAG=${{ inputs.image-tag }}" >> $GITHUB_ENV

    - name: Set KV environment variables
      shell: bash
      run: |
        # tag build to the review env for vars and secrets
        tf_vars_file=terraform/aks/workspace-variables/review.tfvars.json
        echo "KEY_VAULT_NAME=$(jq -r '.key_vault_name' ${tf_vars_file})" >> $GITHUB_ENV
        echo "KEY_VAULT_APP_SECRET_NAME=$(jq -r '.key_vault_app_secret_name' ${tf_vars_file})" >> $GITHUB_ENV

    - uses: azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials }}

    - uses: DFE-Digital/keyvault-yaml-secret@v1
      id: get-secret
      with:
        keyvault: ${{ env.KEY_VAULT_NAME }}
        secret: ${{ env.KEY_VAULT_APP_SECRET_NAME }}
        key: SENTRY_DSN

    - name: Pull docker image
      shell: bash
      run: docker pull ${{ inputs.docker-image }}:${{ inputs.image-tag }}

    - name: Bring image up
      shell: bash
      run: |
        docker-compose up --no-build -d
        docker-compose exec -T web /bin/sh -c "./wait-for-command.sh -c 'nc -z db 5432' -s 0 -t 20"
      env:
        SENTRY_DSN: ${{ steps.get-secret.outputs.sentry_dsn }}
