default: &default
  RAILS_SERVE_STATIC_FILES: true

review:
  <<: *default
  RAILS_ENV: review_aks
  RACK_ENV: review_aks

qa:
  <<: *default
  RAILS_ENV: qa_aks
  RACK_ENV: qa_aks

staging:
  <<: *default
  RAILS_ENV: staging_aks
  RACK_ENV: staging_aks

production:
  <<: *default
  RAILS_ENV: production_aks
  RACK_ENV: production_aks

productiondata:
  <<: *default
  RAILS_ENV: productiondata_aks
  RACK_ENV: productiondata_aks
