default: &default
  RAILS_SERVE_STATIC_FILES: true

review:
  <<: *default
  RAILS_ENV: review
  RACK_ENV: review

qa:
  <<: *default
  RAILS_ENV: qa
  RACK_ENV: qa

staging:
  <<: *default
  RAILS_ENV: staging
  RACK_ENV: staging

pen:
  <<: *default
  RAILS_ENV: pen
  RACK_ENV: pen

production:
  <<: *default
  RAILS_ENV: production
  RACK_ENV: production

sandbox:
  <<: *default
  RAILS_ENV: sandbox
  RACK_ENV: sandbox

productiondata:
  <<: *default
  RAILS_ENV: productiondata
  RACK_ENV: productiondata

csv-sandbox:
  <<: *default
  RAILS_ENV: csv-sandbox
  RACK_ENV: csv-sandbox
