name: smoke-test
description: runs smoke tests

inputs:
  environment:
    description: Environment to run tests in
    required: true
  app-env:
    description: APP Environment
    required: true
  pr-number:
    description: PR number if testing a review app
    required: false
  slack-webhook:
    required: true
  smoke-test-username:
    required: true
  smoke-test-password:
    required: true
  basic-auth-username:
    required: true
  basic-auth-password:
    required: true

runs:
  using: composite
  steps:
    - name: Set up Ruby 3.2.5
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.5

# base_url is set in config_settings for non-review apps and will need to be overridden for aks non-review
    - name: Set Environment variables
      shell: bash
      run: |
        if [ ! -z "${{ inputs.pr-number }}" ]; then
          PR_NUMBER=${{ inputs.pr-number }}
          echo "base_url: https://register-pr-$PR_NUMBER.test.teacherservices.cloud" >> config/settings/review.yml
        fi;

    - name: Bundle smoke test gems
      shell: bash
      run: |
        gem install bundler
        echo 'gem "rspec"' >> Gemfile
        bundle

    - name: Smoke Tests ${{ inputs.environment }}
      shell: bash
      run: RAILS_ENV=${{ inputs.app-env }} ./bin/bundle exec rspec spec/smoke
      env:
        SMOKE_TEST_USERNAME: ${{ inputs.smoke-test-username }}
        SMOKE_TEST_PASSWORD: ${{ inputs.smoke-test-password }}
        BASIC_AUTH_USERNAME: ${{ inputs.basic-auth-username }}
        BASIC_AUTH_PASSWORD: ${{ inputs.basic-auth-password }}
