name: smoke-test
description: runs smoke tests

inputs:
  environment:
    description: Environment to run tests in
    required: true
  app-env:
    description: APP Environment
    required: true
  pr-number:
    description: PR number if testing a review app
    required: false
  slack-webhook:
    required: true

runs:
  using: composite
  steps:
    - name: Set up Ruby 3.1.3
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3

# base_url is set in config_settings for non-review apps and will need to be overriden for aks non-review
    - name: Set Environment variables
      shell: bash
      run: |
        if [ ! -z "${{ inputs.pr-number }}" ]; then
          PR_NUMBER=${{ inputs.pr-number }}
          echo "base_url: https://register-pr-$PR_NUMBER.test.teacherservices.cloud" >> config/settings/review_aks.yml
        fi;

    - name: Bundle smoke test gems
      shell: bash
      run: |
        gem install bundler
        echo 'gem "rspec"' >> Gemfile
        bundle

    - name: Smoke Tests ${{ inputs.environment }}
      shell: bash
      run: RAILS_ENV=${{ inputs.environment }} ./bin/bundle exec rspec spec/smoke

#    - name: 'Nofiy #twd_publish_register_tech on failure'
#      if: ${{ failure() && inputs.environment != 'review' }}
#      uses: rtCamp/action-slack-notify@master
#      env:
#        SLACK_CHANNEL: twd_publish_register_tech
#        SLACK_COLOR: '#ef5343'
#        SLACK_ICON_EMOJI: ':github-logo:'
#        SLACK_USERNAME: Register Trainee Teachers
#        SLACK_TITLE: Smoke tests failure
#        SLACK_MESSAGE: ':alert: Smoke tests failure on ${{ inputs.environment }} :sadparrot:'
#        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
