AGE_RANGES = [
  { name: "3 to 11 programme", option: :main },
  { name: "5 to 11 programme", option: :main },
  { name: "11 to 16 programme", option: :main },
  { name: "11 to 19 programme", option: :main },
  { name: "0 - 5 programme", option: :additional },
  { name: "3 - 7 programme", option: :additional },
  { name: "3 - 8 programme", option: :additional },
  { name: "3 - 9 programme", option: :additional },
  { name: "3 - 11 programme", option: :additional },
  { name: "5 - 9 programme", option: :additional },
  { name: "5 - 11 programme", option: :additional },
  { name: "5 - 14 programme", option: :additional },
  { name: "7 - 11 programme", option: :additional },
  { name: "7 - 14 programme", option: :additional },
  { name: "7 - 16 programme", option: :additional },
  { name: "9 - 14 programme", option: :additional },
  { name: "9 - 16 programme", option: :additional },
  { name: "11 - 16 programme", option: :additional },
  { name: "11 - 19 programme", option: :additional },
  { name: "14 - 19 programme", option: :additional },
  { name: "14 - 19 diploma", option: :additional },
].freeze
