# frozen_string_literal: true

module AllocationSubjects
  ART_AND_DESIGN = "Art and design"
  BIOLOGY = "Biology"
  BUSINESS_STUDIES = "Business studies"
  CHEMISTRY = "Chemistry"
  CLASSICS = "Classics"
  COMPUTING = "Computing"
  DESIGN_AND_TECHNOLOGY = "Design and technology"
  DRAMA = "Drama"
  EARLY_YEARS_ITT = "Early years ITT"
  ECONOMICS = "Economics"
  ENGLISH = "English"
  GEOGRAPHY = "Geography"
  HISTORY = "History"
  MATHEMATICS = "Mathematics"
  MODERN_LANGUAGES = "Modern languages"
  MUSIC = "Music"
  OTHER_SUBJECTS = "Other subjects"
  PHYSICAL_EDUCATION = "Physical education"
  PHYSICS = "Physics"
  PRIMARY = "Primary"
  PRIMARY_WITH_MATHEMATICS = "Primary with mathematics"
  RELIGIOUS_EDUCATION = "Religious education"
end
