INSTITUTIONS = [
  "Aberystwyth University",
  "Anglia Ruskin University",
  "Aston University",
  "Bangor University",
  "Bath Spa University",
  "Birkbeck College",
  "Birmingham City University",
  "Bishop Grosseteste University",
  "Boarshaw Community Primary School",
  "Bournemouth University",
  "Brindishe Green School",
  "Broadclyst Community Primary School",
  "Brunel University London",
  "Buckinghamshire New University",
  "Canterbury Christ Church University",
  "Cardiff Metropolitan University",
  "Cardiff University",
  "Courtauld Institute of Art",
  "Coventry University",
  "Cranfield University",
  "Cumbria Institute of the Arts",
  "Dartington College of Arts",
  "De Montfort University",
  "EAST SCITT",
  "Edge Hill University",
  "Edinburgh Napier University",
  "Falmouth University",
  "Glasgow School of Art",
  "Glyndwr University",
  "Goldsmiths College",
  "Guildhall School of Music and Drama",
  "Harper Adams University",
  "Heriot-Watt University",
  "Heythrop College",
  "Imperial College of Science, Technology and Medicine",
  "Institute of Education",
  "Kent Institute of Art and Design",
  "King's College London",
  "Kingston University",
  "Leeds Beckett University",
  "Leeds College of Art",
  "Leeds College of Music",
  "Leeds Trinity University",
  "Liverpool Hope University",
  "Liverpool John Moores University",
  "London Business School",
  "London Guildhall University",
  "London Metropolitan University",
  "London School of Economics and Political Science",
  "London South Bank University",
  "Loughborough University",
  "Manchester Health Academy",
  "Middlesex University",
  "Newcastle College",
  "Newman University",
  "Non EU countries",
  "Northern School of Contemporary Dance",
  "Norwich City College of Further and Higher Education",
  "Norwich University of the Arts",
  "Not applicable",
  "Not available in EBRDMS",
  "Other EU countries",
  "Other UK",
  "Other UK (Northern Ireland)",
  "Other UK (Scotland)",
  "Other UK (Wales)",
  "Oxford Brookes University",
  "Plymouth Marjon University",
  "Prestolee SCITT",
  "Queen Margaret University, Edinburgh",
  "Queen Mary University of London",
  "Ravensbourne",
  "Roehampton University",
  "Rose Bruford College",
  "Royal Academy of Music",
  "Royal College of Art",
  "Royal College of Music",
  "Royal Holloway and Bedford New College",
  "Royal Northern College of Music",
  "Royal Welsh College of Music and Drama",
  "Salford College of Technology",
  "Sheffield Hallam University",
  "Southampton Solent University",
  "St George's Hospital Medical School",
  "St Mary's University College",
  "St Mary's University, Twickenham",
  "Staffordshire University",
  "Swansea University",
  "Teach First",
  "Teesside University",
  "The Arts University Bournemouth",
  "The City University",
  "The Liverpool Institute for Performing Arts",
  "The Manchester Metropolitan University",
  "The Nottingham Trent University",
  "The Open University",
  "The Queen's University of Belfast",
  "The Royal Central School of Speech and Drama",
  "The Royal Veterinary College",
  "The School of Oriental and African Studies",
  "The Surrey Institute of Art and Design, University College",
  "The University of Aberdeen",
  "The University of Bath",
  "The University of Birmingham",
  "The University of Brighton",
  "The University of Bristol",
  "The University of Buckingham",
  "The University of Cambridge",
  "The University of Central Lancashire",
  "The University of Chichester",
  "The University of Dundee",
  "The University of East Anglia",
  "The University of East London",
  "The University of Edinburgh",
  "The University of Exeter",
  "The University of Glasgow",
  "The University of Greenwich",
  "The University of Hull",
  "The University of Keele",
  "The University of Leeds",
  "The University of Leicester",
  "The University of Lincoln",
  "The University of Liverpool",
  "The University of Manchester",
  "The University of Manchester Institute of Science and Technology",
  "The University of North London",
  "The University of Northampton",
  "The University of Oxford",
  "The University of Portsmouth",
  "The University of Reading",
  "The University of Salford",
  "The University of Sheffield",
  "The University of St Andrews",
  "The University of Stirling",
  "The University of Strathclyde",
  "The University of Sunderland",
  "The University of Wales (central functions)",
  "The University of Wales, Newport",
  "The University of Warwick",
  "The University of West London",
  "The University of York",
  "Trinity Laban Conservatoire of Music and Dance",
  "Trinity University College",
  "University Campus Suffolk",
  "University Church Free School CH1 1QP",
  "University College Birmingham",
  "University College Cardiff",
  "University College London",
  "University for the Creative Arts",
  "University of Bedfordshire",
  "University of Bolton",
  "University of Bradford",
  "University of Chester",
  "University of Cumbria",
  "University of Derby",
  "University of Durham",
  "University of Essex",
  "University of Glamorgan",
  "University of Gloucestershire",
  "University of Hertfordshire",
  "University of Huddersfield",
  "University of Kent",
  "University of Lancaster",
  "University of London",
  "University of Manchester",
  "University of Newcastle-upon-Tyne",
  "University of Northumbria at Newcastle",
  "University of Nottingham",
  "University of Plymouth",
  "University of South Wales",
  "University of Southampton",
  "University of Surrey",
  "University of Sussex",
  "University of the Arts London",
  "University of the West of England, Bristol",
  "University of Ulster",
  "University of Wales Trinity Saint David",
  "University of Wales, Cardiff",
  "University of Westminster",
  "University of Winchester",
  "University of Wolverhampton",
  "University of Worcester",
  "West London Institute of HE",
  "West Suffolk College",
  "Wimbledon School of Art",
  "Winchester School of Art",
  "Writtle College",
  "York St John University",
].sort.freeze
