module Nationalities
  SEED_NATIONALITIES = [
    "Afghan",
    "albanian",
    "algerian",
    "american",
    "andorran",
    "angolan",
    "anguillan",
    "argentine",
    "armenian",
    "australian",
    "austrian",
    "azerbaijani",
    "bahamian",
    "bahraini",
    "bangladeshi",
    "barbadian",
    "belarusian",
    "belgian",
    "belizean",
    "beninese",
    "bermudian",
    "bhutanese",
    "bolivian",
    "botswanan",
    "brazilian",
    "british",
    "british virgin islander",
    "bruneian",
    "bulgarian",
    "burkinan",
    "burmese",
    "burundian",
    "cambodian",
    "cameroonian",
    "canadian",
    "cape verdean",
    "cayman islander",
    "central african",
    "chadian",
    "chilean",
    "chinese",
    "citizen of antigua and barbuda",
    "citizen of bosnia and herzegovina",
    "citizen of guinea-bissau",
    "citizen of kiribati",
    "citizen of seychelles",
    "citizen of the dominican republic",
    "citizen of vanuatu",
    "colombian",
    "comoran",
    "congolese (congo)",
    "congolese (drc)",
    "cook islander",
    "costa rican",
    "croatian",
    "cuban",
    "cymraes",
    "cymro",
    "cypriot",
    "czech",
    "danish",
    "djiboutian",
    "dominican",
    "dutch",
    "east timorese",
    "ecuadorean",
    "egyptian",
    "emirati",
    "equatorial guinean",
    "eritrean",
    "estonian",
    "ethiopian",
    "faroese",
    "fijian",
    "filipino",
    "finnish",
    "french",
    "gabonese",
    "gambian",
    "georgian",
    "german",
    "ghanaian",
    "gibraltarian",
    "greek",
    "greenlandic",
    "grenadian",
    "guamanian",
    "guatemalan",
    "guinean",
    "guyanese",
    "haitian",
    "honduran",
    "hong konger",
    "hungarian",
    "icelandic",
    "indian",
    "indonesian",
    "iranian",
    "iraqi",
    "irish",
    "israeli",
    "italian",
    "ivorian",
    "jamaican",
    "japanese",
    "jordanian",
    "kazakh",
    "kenyan",
    "kittitian",
    "kosovan",
    "kuwaiti",
    "kyrgyz",
    "lao",
    "latvian",
    "lebanese",
    "liberian",
    "libyan",
    "liechtenstein citizen",
    "lithuanian",
    "luxembourger",
    "macanese",
    "macedonian",
    "malagasy",
    "malawian",
    "malaysian",
    "maldivian",
    "malian",
    "maltese",
    "marshallese",
    "martiniquais",
    "mauritanian",
    "mauritian",
    "mexican",
    "micronesian",
    "moldovan",
    "monegasque",
    "mongolian",
    "montenegrin",
    "montserratian",
    "moroccan",
    "mosotho",
    "mozambican",
    "namibian",
    "nauruan",
    "nepalese",
    "new zealander",
    "nicaraguan",
    "nigerian",
    "nigerien",
    "niuean",
    "north korean",
    "norwegian",
    "omani",
    "other",
    "pakistani",
    "palauan",
    "palestinian",
    "panamanian",
    "papua new guinean",
    "paraguayan",
    "peruvian",
    "pitcairn islander",
    "polish",
    "portuguese",
    "prydeinig",
    "puerto rican",
    "qatari",
    "romanian",
    "russian",
    "rwandan",
    "salvadorean",
    "sammarinese",
    "samoan",
    "sao tomean",
    "saudi arabian",
    "senegalese",
    "serbian",
    "sierra leonean",
    "singaporean",
    "slovak",
    "slovenian",
    "solomon islander",
    "somali",
    "south african",
    "south korean",
    "south sudanese",
    "spanish",
    "sri lankan",
    "st helenian",
    "st lucian",
    "stateless",
    "sudanese",
    "surinamese",
    "swazi",
    "swedish",
    "swiss",
    "syrian",
    "taiwanese",
    "tajik",
    "tanzanian",
    "thai",
    "togolese",
    "tongan",
    "trinidadian",
    "tristanian",
    "tunisian",
    "turkish",
    "turkmen",
    "turks and caicos islander",
    "tuvaluan",
    "ugandan",
    "ukrainian",
    "uruguayan",
    "uzbek",
    "vatican citizen",
    "venezuelan",
    "vietnamese",
    "vincentian",
    "wallisian",
    "yemeni",
    "zambian",
    "zimbabwean",
  ].freeze
end
