PROGRAMME_SUBJECTS = [
  { name: "Primary", level: :primary },
  { name: "Primary with English", level: :primary },
  { name: "Primary with geography and history", level: :primary },
  { name: "Primary with mathematics", level: :primary },
  { name: "Primary with modern languages", level: :primary },
  { name: "Primary with physical education", level: :primary },
  { name: "Primary with science", level: :primary },
  { name: "Art and design", level: :secondary },
  { name: "Science", level: :secondary },
  { name: "Biology", level: :secondary },
  { name: "Business studies", level: :secondary },
  { name: "Chemistry", level: :secondary },
  { name: "Citizenship", level: :secondary },
  { name: "Classics", level: :secondary },
  { name: "Communication and media studies", level: :secondary },
  { name: "Computing", level: :secondary },
  { name: "Dance", level: :secondary },
  { name: "Design and technology", level: :secondary },
  { name: "Drama", level: :secondary },
  { name: "Economics", level: :secondary },
  { name: "English", level: :secondary },
  { name: "Geography", level: :secondary },
  { name: "Health and social care", level: :secondary },
  { name: "History", level: :secondary },
  { name: "Mathematics", level: :secondary },
  { name: "Music", level: :secondary },
  { name: "Philosophy", level: :secondary },
  { name: "Physical education", level: :secondary },
  { name: "Physics", level: :secondary },
  { name: "Psychology", level: :secondary },
  { name: "Religious education", level: :secondary },
  { name: "Social sciences", level: :secondary },
  { name: "French", level: :secondary },
  { name: "English as a second or other language", level: :secondary },
  { name: "German", level: :secondary },
  { name: "Italian", level: :secondary },
  { name: "Japanese", level: :secondary },
  { name: "Mandarin", level: :secondary },
  { name: "Russian", level: :secondary },
  { name: "Spanish", level: :secondary },
  { name: "Modern languages (other)", level: :secondary },
  { name: "Further education", level: :further_education },
].freeze
