# frozen_string_literal: true

SUBJECTS = [
  "Ceramics",
  "Clinical engineering",
  "Metallurgy",
  "Musical theatre",
  "Optometry",
  "Orthoptics",
  "Pathobiology",
  "Creative writing",
  "Design",
  "Product design",
  "Textile design",
  "Ergonomics",
  "Fashion",
  "Fashion design",
  "Animation",
  "Film studies",
  "Fine art",
  "Graphic arts",
  "Graphic design",
  "Illustration",
  "Photography",
  "Liberal arts",
  "Acting",
  "Dance",
  "Drama",
  "Music",
  "Performing arts",
  "Advertising",
  "Marketing",
  "Public relations",
  "Business and management",
  "Business studies",
  "International business",
  "Event management",
  "Hospitality management",
  "Human resource management",
  "International hospitality management",
  "Leadership",
  "Management studies",
  "Public administration",
  "Public services",
  "Retail management",
  "Logistics",
  "Sports coaching",
  "Sports development",
  "Sports management",
  "Sports studies",
  "Tourism management",
  "Travel and tourism",
  "Travel management",
  "Accountancy",
  "Accounting",
  "Actuarial science",
  "Finance",
  "Clothing production",
  "Footwear production",
  "Aeronautical engineering",
  "Aerospace engineering",
  "Space technology",
  "Avionics",
  "Satellite engineering",
  "Architectural engineering",
  "Architectural technology",
  "Architecture",
  "Landscape architecture and design",
  "Biomechanics",
  "Biomedical engineering",
  "Dental technology",
  "Diagnostic imaging",
  "Prosthetics and orthotics",
  "Radiology",
  "Therapeutic imaging",
  "Biotechnology",
  "Bioprocessing",
  "Environmental biotechnology",
  "Industrial biotechnology",
  "Medical biotechnology",
  "Plant biotechnology",
  "Biochemical engineering",
  "Chemical engineering",
  "Pharmaceutical engineering",
  "Polymer science and technology",
  "Building services engineering",
  "Civil engineering",
  "Construction",
  "Construction and the built environment",
  "Construction management",
  "Offshore engineering",
  "Structural engineering",
  "Transport engineering",
  "Minerals technology",
  "Highways engineering",
  "Railway engineering",
  "Telecommunications engineering",
  "Computer aided engineering",
  "Computer systems engineering",
  "Electrical and electronic engineering",
  "Electrical engineering",
  "Electronic engineering",
  "Control systems",
  "Microelectronic engineering",
  "Optoelectronic engineering",
  "Mechatronics and robotics",
  "Nuclear engineering",
  "Energy engineering",
  "Gas engineering",
  "Microwave engineering",
  "Petroleum engineering",
  "Environmental engineering",
  "Engineering design",
  "Fire safety engineering",
  "General or integrated engineering",
  "Safety engineering",
  "Emergency and disaster technologies",
  "Systems engineering",
  "Mechanical engineering",
  "Electromechanical engineering",
  "Maintenance engineering",
  "Marine technology",
  "Housing",
  "Planning",
  "Transport planning",
  "Urban and regional planning",
  "Automotive engineering",
  "Manufacturing engineering",
  "Materials engineering",
  "Mining engineering",
  "Motorcycle engineering",
  "Motorsport engineering",
  "Naval architecture",
  "Production and manufacturing engineering",
  "Leather technology",
  "Fabrication",
  "Minerals processing",
  "Quality management",
  "Textiles technology",
  "Building surveying",
  "Quantity surveying",
  "Real estate",
  "Surveying",
  "Music technology",
  "Audio technology",
  "Music production",
  "Materials science",
  "Aviation studies",
  "Navigation",
  "Acupuncture",
  "Alternative medicines and therapies",
  "Aromatherapy",
  "Chinese medical techniques",
  "Herbal medicine",
  "Reflexology",
  "Chiropractic",
  "Complementary medicines and therapies",
  "Osteopathy",
  "Health sciences",
  "Nutrition",
  "Occupational health",
  "Occupational therapy",
  "Pharmacology",
  "Pharmacy",
  "Physiotherapy",
  "Podiatry",
  "Psychotherapy",
  "Speech and language therapy",
  "Audiology",
  "Clinical physiology",
  "Genetics",
  "Healthcare science",
  "Ophthalmology",
  "Physiology",
  "Anatomy",
  "Biomedical sciences",
  "Clinical dentistry",
  "Clinical medicine",
  "Dentistry",
  "Medical sciences",
  "Medicine",
  "Neuroscience",
  "Operating department practice",
  "Pathology",
  "Pre-clinical dentistry",
  "Pre-clinical medicine",
  "Toxicology",
  "Adult nursing",
  "Children's nursing",
  "Community nursing",
  "Critical care nursing",
  "Dental nursing",
  "Emergency nursing",
  "General practice nursing",
  "Learning disabilities nursing",
  "Mental health nursing",
  "Midwifery",
  "Neonatal nursing",
  "Nursing",
  "Older people nursing",
  "Palliative care nursing",
  "School nursing",
  "Theatre nursing",
  "Health visiting",
  "Ancient history",
  "Archaeology",
  "Classical studies",
  "Economic history",
  "History",
  "History of art",
  "History of science",
  "Local history",
  "Medieval history",
  "Modern history",
  "Scottish history",
  "Social history",
  "Humanities",
  "American studies",
  "British Sign Language studies",
  "English language",
  "English literature",
  "English studies",
  "French language",
  "French studies",
  "German language",
  "German studies",
  "Spanish studies",
  "Italian language",
  "Italian studies",
  "Linguistics",
  "Modern languages",
  "Russian languages",
  "Russian and East European studies",
  "Spanish language",
  "Welsh language",
  "Welsh studies",
  "Philosophy",
  "Philosophy of science",
  "Religious studies",
  "Theology",
  "Applied biology",
  "Biochemistry",
  "Biological sciences",
  "Biology",
  "Ecology",
  "Environmental biology",
  "Human biology",
  "Marine biology",
  "Medical biochemistry",
  "Microbiology",
  "Molecular biology",
  "Plant sciences",
  "Zoology",
  "Applied computing",
  "Artificial intelligence",
  "Business computing",
  "Business information systems",
  "Business information technology",
  "Computer animation and visual effects",
  "Computer networks",
  "Computer science",
  "Computing and information technology",
  "Creative computing",
  "Geographical information systems",
  "Information management",
  "Information systems",
  "Information technology",
  "Internet technologies",
  "Software engineering",
  "Web and multimedia design",
  "Computer and information security",
  "Climate science",
  "Environmental geoscience",
  "Environmental sciences",
  "Meteorology",
  "Archaeological sciences",
  "Computer forensics",
  "Forensic biology",
  "Forensic psychology",
  "Forensic science",
  "General science",
  "Natural sciences",
  "Applied science",
  "Earth sciences",
  "Geology",
  "Geophysics",
  "Palaeontology",
  "Applied mathematics",
  "Financial mathematics",
  "Mathematical modelling",
  "Mathematics",
  "Operational research",
  "Pure mathematics",
  "Statistics",
  "Environmental geography",
  "Geography",
  "Physical geography",
  "Analytical chemistry",
  "Astronomy",
  "Astrophysics",
  "Chemical physics",
  "Chemistry",
  "Marine sciences",
  "Medical physics",
  "Medicinal chemistry",
  "Ocean sciences",
  "Organic chemistry",
  "Pharmaceutical chemistry",
  "Physical sciences",
  "Physics",
  "Theoretical physics",
  "Acoustics",
  "Aerodynamics",
  "Dynamics",
  "Mechanics",
  "Thermodynamics",
  "Sport and exercise sciences",
  "Anthropology",
  "Social anthropology",
  "Broadcast journalism",
  "Digital media",
  "Film production",
  "Journalism",
  "Media production",
  "Media and communication studies",
  "Multimedia journalism",
  "Business economics",
  "Economics",
  "Financial economics",
  "International economics",
  "Adult education",
  "Childhood and youth studies",
  "Childhood studies",
  "Early childhood studies",
  "Education studies",
  "Further education",
  "Higher education",
  "Learning support",
  "Early years education",
  "Primary education",
  "Secondary education",
  "Youth and community work",
  "Countryside management",
  "Environmental management",
  "Social sciences",
  "Health studies",
  "Sports therapy",
  "Health and social care",
  "Human geography",
  "Business law",
  "Criminal justice",
  "Criminology",
  "Law",
  "Policing",
  "International development",
  "International politics",
  "International relations",
  "Politics",
  "Applied psychology",
  "Clinical psychology",
  "Counselling",
  "Educational psychology",
  "Psychology",
  "Social psychology",
  "Sport and exercise psychology",
  "Social care",
  "Social policy",
  "Social work",
  "Sociology",
  "Adult education teaching",
  "Post compulsory education and training",
  "Higher education teaching",
  "Early years teaching",
  "Primary teaching",
  "Secondary teaching",
  "Teaching English as a foreign language",
  "Agricultural sciences",
  "Agriculture",
  "Animal management",
  "Equine studies",
  "Forestry and arboriculture",
  "Animal behaviour",
  "Animal science",
  "Food and beverage production",
  "Food science",
  "Horticulture",
  "Veterinary medicine",
  "Veterinary nursing",
  "Broadcast engineering",
  "Cellular pathology",
  "Marine engineering",
  "Corrosion technology",
  "Digital circuit engineering",
  "Engineering surveying",
  "Environmental impact assessment",
  "Gemmology",
  "Geotechnical engineering",
  "Integrated circuit design",
  "Musical instrument manufacture",
  "Aerospace propulsion systems",
  "Public health engineering",
  "Quarrying",
  "Ship design",
  "Tissue engineering and regenerative medicine",
  "Water quality control",
  "Fluid mechanics",
  "Structural mechanics",
  "Acoustics and vibration",
  "Electrical power",
  "Architectural design",
  "Building technology",
  "Conservation of buildings",
  "Property development",
  "Drawing",
  "Landscape studies",
  "Painting",
  "Garden design",
  "Sculpture",
  "Rural planning",
  "Urban studies",
  "Printmaking",
  "Applied economics",
  "Fine art conservation",
  "Agricultural economics",
  "Economic policy",
  "Econometrics",
  "Economic systems",
  "Democracy",
  "UK government/parliamentary studies",
  "European Union politics",
  "Strategic studies",
  "War and peace studies",
  "Comparative politics",
  "Applied sociology",
  "Gender studies",
  "Women's studies",
  "Men's studies",
  "Ethnicity",
  "Disability studies",
  "Religion in society",
  "Socio-economics",
  "Social theory",
  "Political sociology",
  "Typography",
  "Sociology of science and technology",
  "Visual communication",
  "Furniture design and making",
  "Interactive and electronic design",
  "Musicianship and performance studies",
  "Instrumental or vocal performance",
  "Music education and teaching",
  "Music and arts management",
  "Music marketing",
  "International social policy",
  "Public policy",
  "Health policy",
  "Welfare policy",
  "Conducting",
  "Education policy",
  "Security policy",
  "Health and welfare",
  "Child care",
  "Community work",
  "Jazz performance",
  "Popular music performance",
  "Careers guidance",
  "Community justice",
  "Historical performance practice",
  "Probation/after-care",
  "Physical and biological anthropology",
  "History of music",
  "Economic geography",
  "Urban geography",
  "Musicology",
  "Political geography",
  "Transport geography",
  "Environmental history",
  "Cultural geography",
  "Ethnomusicology and world music",
  "English law",
  "Northern Irish law",
  "Scots law",
  "European Union law",
  "Public international law",
  "Comparative law",
  "Public law",
  "Criminal law",
  "Private law",
  "Property law",
  "Torts",
  "Jurisprudence",
  "Legal practice",
  "Medical law",
  "Music composition",
  "Directing for theatre",
  "Theatre studies",
  "Theatre production",
  "Technical theatre studies",
  "Stage management",
  "Technical stage management",
  "Theatrical wardrobe design",
  "Hair and make-up",
  "Circus arts",
  "Stage design",
  "Community theatre",
  "Choreography",
  "Dance performance",
  "History of photography",
  "Cinematography",
  "Visual and audio effects",
  "Metal work",
  "Glass crafts",
  "Silversmithing and goldsmithing",
  "Clock and watchmaking",
  "Surface decoration",
  "Scriptwriting",
  "Poetry writing",
  "Professional writing",
  "Computer architectures",
  "Operating systems",
  "Human-computer interaction",
  "Multimedia computing science",
  "E-business",
  "Beauty therapy",
  "High performance computing",
  "Systems thinking",
  "Dietetics",
  "Clinical practice nursing",
  "Medical nursing",
  "Cardiology",
  "Paramedic science",
  "Physician associate studies",
  "Information modelling",
  "Systems analysis and design",
  "Databases",
  "Data management",
  "Systems auditing",
  "Intelligent systems",
  "British history",
  "Irish history",
  "Welsh history",
  "English history",
  "European history",
  "German history",
  "Italian history",
  "Iberian studies",
  "Russian history",
  "American history",
  "USA history",
  "Latin American history",
  "Chinese history",
  "South Asian history",
  "South East Asian history",
  "Byzantine studies",
  "World history",
  "International history",
  "Family history",
  "History of religions",
  "Intellectual history",
  "History of architecture",
  "History of design",
  "History of mathematics",
  "History of medicine",
  "Military history",
  "Egyptology",
  "Mental philosophy",
  "Social philosophy",
  "Ethics",
  "Theology and religious studies",
  "Christian studies",
  "Islamic studies",
  "Judaism",
  "Buddhism",
  "Divinity",
  "Religious writings",
  "Biblical studies",
  "Pastoral studies",
  "Comparative religious studies",
  "Heritage studies",
  "Heritage management",
  "European business studies",
  "Strategic management",
  "Creative management",
  "Project management",
  "Change management",
  "Organisational development",
  "Institutional management",
  "Management and organisation of education",
  "Land management",
  "Property management",
  "Requirements engineering",
  "Cell biology",
  "Emergency and disaster management",
  "Property valuation and auctioneering",
  "Parasitology",
  "Banking",
  "Investment",
  "Behavioural biology",
  "Insurance",
  "Taxation",
  "Financial management",
  "Developmental biology",
  "Financial risk",
  "Management accountancy",
  "Public accountancy",
  "Book-keeping",
  "Audit management",
  "Popular music",
  "Film music and screen music",
  "Jazz",
  "Sacred music",
  "Financial reporting",
  "Market research",
  "Reproductive biology",
  "Aquatic biology",
  "Freshwater biology",
  "Population biology",
  "Sales management",
  "International marketing",
  "Community music",
  "Promotion and advertising",
  "Corporate image",
  "Evolution",
  "Staff development",
  "Sonic arts",
  "Ecosystem ecology and land use",
  "Biometry",
  "Health and safety management",
  "Electronic music",
  "Office administration",
  "Bioinformatics",
  "Jazz composition",
  "Mycology",
  "Plant cell science",
  "Plant pathology",
  "Tourism",
  "Applied zoology",
  "Cell zoology",
  "Entomology",
  "Marine zoology",
  "Pest management",
  "Ballet",
  "Contemporary dance",
  "Moving image techniques",
  "Film directing",
  "Film and sound recording",
  "Hospitality",
  "Recreation and leisure studies",
  "Spa management",
  "Crafts",
  "Salon management",
  "Human genetics",
  "Medical genetics",
  "Molecular genetics",
  "Genomics",
  "Population genetics",
  "Applied microbiology",
  "Medical microbiology",
  "Veterinary microbiology",
  "Bacteriology",
  "Virology",
  "Immunology",
  "Blood sciences",
  "Librarianship",
  "Curatorial studies",
  "Archives and records management",
  "Information services",
  "Museum studies",
  "Publicity studies",
  "Television studies",
  "Radio studies",
  "Paper-based media studies",
  "Television production",
  "Radio production",
  "Publishing",
  "Electronic publishing",
  "Online publishing",
  "Plant biochemistry",
  "Animal health",
  "Animal physiology",
  "Veterinary pathology",
  "Veterinary pharmacology",
  "Animal nutrition",
  "Veterinary pharmacy",
  "Veterinary public health",
  "Crop protection",
  "Crop nutrition",
  "Crop production",
  "Biomolecular science",
  "Biophysical science",
  "Occupational psychology",
  "Developmental psychology",
  "Child psychology",
  "Business psychology",
  "Programming",
  "Psychology of ageing",
  "Research methods in psychology",
  "Object-oriented programming",
  "Natural language processing",
  "Research skills",
  "Knowledge and information systems",
  "Neural computing",
  "Computer vision",
  "Applied linguistics",
  "Phonetics and phonology",
  "Phonetics",
  "Phonology",
  "Livestock",
  "Aquaculture",
  "Rural estate management",
  "Farm management",
  "Game keeping management",
  "Health psychology",
  "Water resource management",
  "Cognitive modelling",
  "Land management for recreation",
  "Machine learning",
  "Cognitive psychology",
  "Health informatics",
  "Sustainable agriculture and landscape development",
  "International agriculture",
  "Psychology of religion",
  "Organic farming",
  "Agricultural technology",
  "Agricultural machinery",
  "Timber engineering",
  "Community forestry",
  "Sociolinguistics",
  "Food and beverage studies",
  "Food safety",
  "Computer games graphics",
  "Computer games programming",
  "Baking technology management",
  "Brewing",
  "Agricultural chemistry",
  "Agricultural botany",
  "Numerical analysis",
  "Engineering and industrial mathematics",
  "Computational mathematics",
  "Applied statistics",
  "Medical statistics",
  "Probability",
  "Stochastic processes",
  "Statistical modelling",
  "Psycholinguistics",
  "Comparative literary studies",
  "Applied chemistry",
  "Risk management",
  "Industrial chemistry",
  "Colour chemistry",
  "Inorganic chemistry",
  "Crystallography",
  "Environmental chemistry",
  "Marine chemistry",
  "Environmental risk",
  "Health risk",
  "Physical chemistry",
  "Polymer chemistry",
  "Oil and gas chemistry",
  "Remote sensing",
  "Mapping science",
  "Applied physics",
  "Engineering physics",
  "Geomorphology",
  "Maritime geography",
  "Soil science",
  "Atmospheric physics",
  "Climate change",
  "Computational physics",
  "Pollution control",
  "Hydrography",
  "Radiation physics",
  "Photonics and optical physics",
  "Laser physics",
  "Nuclear and particle physics",
  "Applied environmental sciences",
  "Hydrology",
  "Volcanology",
  "Geological hazards",
  "Geochemistry",
  "Exploration geophysics",
  "Specialist teaching",
  "Geological oceanography",
  "Special needs teaching",
  "Research and study skills in education",
  "Hydrogeology",
  "Study skills",
  "Quaternary studies",
  "Exploration geology",
  "English literature 1200 - 1700",
  "English literature 1700 - 1900",
  "Space science",
  "Planetary science",
  "Applied geology",
  "Petroleum geology",
  "Engineering geology",
  "Shakespeare studies",
  "Colonial and post-colonial literature",
  "English as a second language",
  "Scottish literature",
  "Ancient Middle Eastern languages",
  "Ancient Egyptian studies",
  "Classical Arabic",
  "Sanskrit studies",
  "Ancient Hebrew language",
  "Celtic studies",
  "Gaelic language",
  "Irish language",
  "Latin studies",
  "Latin literature",
  "Classical Greek studies",
  "Classical reception",
  "Translation studies",
  "French literature",
  "French society and culture",
  "German literature",
  "German society and culture",
  "Italian society and culture",
  "Italian literature",
  "Spanish society and culture",
  "Spanish literature",
  "Portuguese studies",
  "Portuguese language",
  "Brazilian studies",
  "Portuguese society and culture",
  "Scandinavian studies",
  "Swedish language",
  "Norwegian language",
  "Finnish language",
  "Russian studies",
  "Polish studies",
  "Polish language",
  "Czech language",
  "Russian literature",
  "Russian and East European society and culture",
  "European studies",
  "Dutch studies",
  "Welsh literature",
  "Chinese studies",
  "Chinese languages",
  "Chinese literature",
  "Chinese society and culture studies",
  "Japanese studies",
  "Japanese languages",
  "Japanese literature",
  "Japanese society and culture studies",
  "South Asian studies",
  "Hindi language",
  "Urdu language",
  "Bengali language",
  "Indian society and culture studies",
  "Asian studies",
  "African studies",
  "African languages",
  "African literature",
  "African society and culture studies",
  "Modern Middle Eastern studies",
  "Modern Middle Eastern languages",
  "Arabic languages",
  "Persian languages",
  "Israeli studies",
  "Turkish studies",
  "Modern Middle Eastern literature",
  "Modern Middle Eastern society and culture studies",
  "Arab society and culture studies",
  "Latin American studies",
  "Latin American literature",
  "Latin American society and culture studies",
  "North American literature studies",
  "North American society and culture studies",
  "Canadian studies",
  "Australasian studies",
  "Caribbean studies",
  "Biomaterials",
  "Korean studies",
  "Cinematics",
  "Food marketing",
  "Bioelectronics",
  "Composite materials",
  "Forensic anthropology",
  "Forensic archaeology",
  "Veterinary epidemiology",
  "Enterprise and entrepreneurship",
  "Crime scene investigation",
  "Condensed matter physics",
  "Cultural studies",
  "Nanotechnology",
  "Music therapy",
  "Bioengineering",
  "Professional practice in education",
  "French history",
  "Thai language",
  "Maritime archaeology",
  "Computer games",
  "Computer games design",
  "Modern Hebrew language",
  "East Asian studies",
  "Combined studies",
  "General studies",
  "Negotiated studies",
  "Work placement experience (personal learning)",
  "Work-based learning",
  "Employability skills (personal learning)",
  "Advice and guidance (personal learning)",
  "International studies",
  "Rehabilitation studies",
  "Neurological rehabilitation",
  "Cardiovascular rehabilitation",
  "Coaching psychology",
  "Quantum theory and applications",
  "Applied social science",
  "Facilities management",
  "Obstetrics and gynaecology",
  "Hungarian studies",
  "Czech studies",
  "Irish studies",
  "Interior design and architecture",
  "Environmental and public health",
  "Biodiversity conservation",
  "Exercise for health",
  "Art psychotherapy",
  "Mentorship",
  "Dispute resolution",
  "Orthopaedics",
  "Paediatrics",
  "Gerontology",
  "Oncology",
  "Dementia studies",
  "Ultrasound",
  "Gastroenterology",
  "Drug and alcohol studies",
  "Epilepsy care",
  "Allergy",
  "Epidemiology",
  "Anaesthesia",
  "Endocrinology",
  "Diabetes",
  "Dermatology",
  "Hypnotherapy",
  "Psychology of communication",
  "Psychology of memory and learning",
  "Transpersonal psychology",
  "Psychobiology",
  "Evolutionary psychology",
  "Veterinary dentistry",
  "Exotic plants and crops",
  "Atmosphere-ocean interactions",
  "Biogeography",
  "Electrical power generation",
  "Electrical power distribution",
  "Cybernetics",
  "Paper technology",
  "Nationalism",
  "Development in Africa",
  "Development in the Americas",
  "African history",
  "Creative arts and design",
  "Calligraphy",
  "Psychology of music",
  "Swahili and other Bantu languages",
  "Hausa language",
  "Indonesian language",
  "Vietnamese language",
  "Nepali language",
  "South East Asian studies",
  "Hair and beauty sciences",
  "Hair services",
  "Spa and water-based therapies",
  "Applied botany",
  "Transcriptomics",
  "Genetic engineering",
  "Sport technology",
  "Metabolic biochemistry",
  "Cognitive neuroscience",
  "Affective neuroscience",
  "Psychometrics",
  "Pre-clinical veterinary medicine",
  "Agricultural irrigation and drainage",
  "Meat science",
  "Cereal science",
  "Organometallic chemistry",
  "Marine physics",
  "Electromagnetism",
  "Glaciology and cryospheric systems",
  "Solid mechanics",
  "Turbine technology",
  "Rail vehicle engineering",
  "Analogue circuit engineering",
  "Parallel computing",
  "Microeconomics",
  "Macroeconomics",
  "Feminism",
  "Anarchism",
  "Victimology",
  "Transport policy",
  "Agricultural geography",
  "Human demography",
  "Shorthand and shorthand transcription",
  "Historical linguistics",
  "Scots language",
  "Irish language literature",
  "Coptic language",
  "Akkadian language",
  "Sumerian language",
  "Aramaic language",
  "Breton language",
  "Latin language",
  "Medieval Latin language",
  "Classical church Greek",
  "Classical Greek literature",
  "Danish language",
  "Scandinavian literature",
  "Estonian language",
  "Hungarian language",
  "South Slavonic languages",
  "Ukranian language",
  "Indian literature studies",
  "Turkish languages",
  "Arabic literature",
  "Persian literature studies",
  "Turkish literature",
  "Oral history",
  "Crime history",
  "Stone Age",
  "Bronze Age",
  "Iron Age",
  "Classical art and archaeology",
  "Metaphysics",
  "Epistemology",
  "Scholastic philosophy",
  "Hinduism",
  "The Qur'an and Islamic texts",
  "The Torah and Judaic texts",
  "Folk music",
  "Opera",
  "Music theory and analysis",
  "Applied music and musicianship",
  "Popular music composition",
  "Body awareness",
  "Dance and culture",
  "Community dance",
  "Stone crafts",
  "Community ecology",
  "Population ecology",
  "Ecotoxicology",
  "Plant physiology",
  "Veterinary biochemistry",
  "Quantitative psychology",
  "Qualitative psychology",
  "Psychopharmacology",
  "Sociology of law",
  "Ruskin studies",
  "John Donne studies",
  "T.S. Eliot studies",
  "Thomas Hardy studies",
  "Oscar Wilde studies",
  "Chaucer studies",
  "Brontës studies",
  "Thomas Pynchon studies",
  "Philip Larkin studies",
  "D.H. Lawrence studies",
  "Charles Dickens studies",
  "Jane Austen studies",
  "James Joyce studies",
  "Margaret Atwood studies",
  "Samuel Beckett studies",
  "Wilkie Collins studies",
  "Byron studies",
  "Shelley studies",
  "Milton studies",
  "J. M. Coetzee studies",
  "Christopher Marlowe studies",
  "Walter Scott studies",
  "Robert Louis Stevenson studies",
  "Robert Burns studies",
  "Virginia Woolf studies",
  "Bob Dylan studies",
  "Dylan Thomas studies",
  "W. B. Yeats studies",
  "Joseph Conrad studies",
  "Salman Rushdie studies",
  "Gaelic literature",
  "Scandinavian history",
  "Russian society and culture",
  "Polish society and culture",
  "Czech society and culture",
  "Persian society and culture studies",
  "Turkish society and culture studies",
  "Carpentry and joinery",
  "Liberalism",
  "Conservatism",
  "Socialism",
  "Fascism",
  "Environmentalism",
  "Ophthalmic dispensing",
].sort.freeze
