plugins: rubocop-rspec

RSpec/NestedGroups:
  Enabled: true
  Max: 4

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

# It's better to be explicit about the class that's being tested
RSpec/DescribedClass:
  Enabled: false

# This cop wants us to use `expect().to change(Candidate, :count)` instead
# of `expect().to change { Candidate.count }`, which does not seem better.
RSpec/ExpectChange:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

# In acceptance tests it's often handy to user instance variables to keep track of state
RSpec/InstanceVariable:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/Dialect:
  PreferredMethods:
    - "scenario"
    - "feature"
    - "background"

RSpec/MessageChain:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - "spec/**/*"

RSpec/NoExpectationExample:
  Enabled: false

# This enables `let` names like `thing1` and `thing2`
RSpec/IndexedLet:
  Enabled: false
