version: "3.4"
volumes:
  dbdata:
services:
  db:
    image: postgres:11-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=developmentpassword

  redis:
    image: redis

  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      cache_from:
        - ghcr.io/dfe-digital/register-trainee-teachers:${IMAGE_TAG:-main}
    image: ghcr.io/dfe-digital/register-trainee-teachers:${IMAGE_TAG:-main}
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=developmentpassword
      - REDIS_CACHE_URL=redis://redis:6379
      - SENTRY_DSN=${SENTRY_DSN}

  bg-jobs:
    image: ghcr.io/dfe-digital/register-trainee-teachers:${IMAGE_TAG:-main}
    command: bundle exec sidekiq -c 5 -C config/sidekiq.yml
    depends_on:
      - web
      - db
      - redis
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=developmentpassword
      - SETTINGS__APPLICATION=register-trainee-teachers-bg-jobs
      - REDIS_QUEUE_URL=redis://redis:6379
