shared:
  event_filters:
    -
      event_type: update_entity
      entity_table_name: trainees
      data:
        key: id
        value: 1817
    -
      event_type: import_entity
      entity_table_name: trainees 
