shared:
  feedback_items:
    - name
    - email
  trainees:
    - first_names
    - last_name
    - email
    - date_of_birth
    - trn
    - searchable
    - middle_names
    - ethnic_background
    - additional_ethnic_background
    - additional_dttp_data
    - provider_trainee_id
  trainee_withdrawals:
    - safeguarding_concern_reasons
  users:
    - dfe_sign_in_uid
    - email
    - first_name
    - last_name
