# frozen_string_literal: true

module Hesa
  module CodeSets
    module DegreeTypes
      # https://www.hesa.ac.uk/collection/c21053/xml/c21053/c21053codelists.xsd

      MAPPING = {
        "001" => "BEd",
        "002" => "BEd (Hons)",
        "003" => "BSc/Education",
        "004" => "BSc Hons /Education",
        "005" => "BTech/Education",
        "006" => "BTech (Hons) /Education",
        "007" => "BA/Education",
        "008" => "BA (Hons) /Education",
        "009" => "BA Combined Studies/Education of the Deaf",
        "010" => "BA (Hons) Combined Studies/Education of the Deaf",
        "012" => "BA with intercalated PGCE",
        "013" => "BSc (Hons) with intercalated PGCE",
        "014" => "BA (Hons) with intercalated PGCE",
        "051" => "Bachelor of Arts(BA)",
        "052" => "Bachelor of Arts Economics(BA ECON)",
        "053" => "Bachelor of Arts in Architecture(BA ARCH)",
        "054" => "Bachelor of the Art of Obstetrics (BAO)",
        "055" => "Bachelor of Architecture(BA ARCH)",
        "056" => "Bachelor of Applied Science(B ASC)",
        "057" => "Bachelor of Agriculture(B AG)",
        "058" => "Bachelor of Accountancy(B ACC)",
        "059" => "Bachelor of Administration(B ADMIN)",
        "060" => "Bachelor of Business Administration(BBA)",
        "061" => "Bachelor of Combined Studies (BCS)",
        "062" => "Bachelor of Commerce(B COMM)",
        "063" => "Bachelor of Divinity(BD)",
        "064" => "Bachelor of Dental Surgery(BDS)",
        "065" => "Bachelor of Engineering(B ENG)",
        "066" => "Bachelor of Engineering with Business Studies(B ENG/BS)",
        "067" => "Bachelor of Fine Art(BFA)",
        "068" => "Bachelor of General Studies(BGS)",
        "069" => "Bachelor of Humanities (BH)",
        "070" => "Bachelor of Hygiene (B HYG)",
        "071" => "Bachelor of Law(LLB)",
        "072" => "Bachelor of Librarianship (B LIB)",
        "073" => "Bachelor of Librarianship and Info. Studies(BLS)",
        "074" => "Bachelor of Literature (B LITT)",
        "075" => "Bachelor of Land Economy(BL ECON)",
        "076" => "Bachelor of Medical Science(B MED SC)",
        "077" => "Bachelor of Medicine(BM)",
        "078" => "Bachelor of Metallurgy (B MET)",
        "079" => "Bachelor of Metallurgy and Engineering(B MET/EN)",
        "080" => "Bachelor of Music (B MU)",
        "081" => "Bachelor of Nursing (BN)",
        "082" => "Bachelor of Pharmacy(B PHARM)",
        "083" => "Bachelor of Science (B SC)",
        "084" => "Bachelor of Science Economics (BSC/ECO)",
        "085" => "Bachelor of Science &amp; Engineering (BSC/ENG)",
        "086" => "Bachelor of Science &amp; Technology (BSC/TEC)",
        "087" => "Bachelor of Science in Social Science (BSC SS)",
        "088" => "Bachelor of Science in Speech Therapy (BSC SPT)",
        "089" => "Bachelor of Social Science (BSS)",
        "090" => "Bachelor of Surgery (BS)",
        "091" => "Bachelor of Chirurgiae (B CH)",
        "092" => "Bachelor of Technology (B TECH)",
        "093" => "Bachelor of Theology (B THEOL)",
        "094" => "Bachelor of Veterinary Medicine (B VMED)",
        "095" => "Bachelor of Veterinary Medicine and Surgery (BVMS)",
        "096" => "Bachelor of Veterinary Science (B VSC)",
        "097" => "Bachelor of Education Scotland &amp; N Ireland (B ED)",
        "098" => "Bachelor of Philosophy (B PHIL)",
        "200" => "Master of Arts (MA)",
        "201" => "Master of Librarianship (M LIB)",
        "202" => "Master of Literature (M LITT)",
        "203" => "Master of Music (M MUS)",
        "204" => "Master of Philosophy (M PHIL)",
        "205" => "Master of Science (M SC)",
        "206" => "Master of Theology (M THEOL)",
        "207" => "Certificate of Membership of Cranfield Institute of Technology",
        "208" => "Master of Education (M ED)",
        "209" => "Master of Business Studies (M BS)",
        "210" => "Master of Social Studies (M SS)",
        "211" => "Master of Engineering (M ENG)",
        "212" => "Master of Law (M LAW)",
        "213" => "Master of Business Administration (MBA)",
        "214" => "Master of Chemistry (M CHEM)",
        "215" => "Master of Physics (M PHYS)",
        "300" => "Doctor of Divinity (DD)",
        "301" => "Doctor of Civil Law (DCL)",
        "302" => "Doctor of Medicine (MD)",
        "303" => "Doctor of Music (D MU)",
        "304" => "Doctor of Science (D SC)",
        "305" => "Doctor of Philosophy (D PHIL)",
        "306" => "PhD (PHD)",
        "400" => "First Degree",
        "401" => "Higher Degree",
        "402" => "Degree equivalent (inc. foreign qualifications)",
        "999" => "Unknown",
      }.freeze
    end
  end
end
