# The url for this app, also used by `dfe_sign_in`
base_url: https://register-productiondata.teacherservices.cloud

dttp:
  scope: https://dttp.crm4.dynamics.com/.default
  api_base_url: https://dttp.crm4.dynamics.com/api/data/v9.1

dqt:
  base_url: https://preprod.teacher-qualifications-api.education.gov.uk

trs:
  base_url: https://preprod.teacher-qualifications-api.education.gov.uk/

dfe_sign_in:
  # URL that the users are redirected to for signing in
  issuer: https://oidc.signin.education.gov.uk
  # URL of the users profile
  profile: https://profile.signin.education.gov.uk

features:
  basic_auth: true
  sign_in_method: dfe-sign-in
  enable_feedback_link: false
  import_courses_from_ttapi: true
  import_applications_from_apply: true
  publish_course_details: true
  routes:
    assessment_only: true
    early_years_assessment_only: true
    early_years_postgrad: true
    early_years_salaried: true
    early_years_undergrad: true
    opt_in_undergrad: true
    pg_teaching_apprenticeship: true
    provider_led_postgrad: true
    provider_led_undergrad: true
    school_direct_salaried: true
    school_direct_tuition_fee: true
    iqts: true
  google:
    send_data_to_big_query: false
  integrate_with_dqt: false
  integrate_with_trs: false
  hesa_import:
    test_mode: true
    sync_trn_data: false
  register_api: false

environment:
  name: productiondata
  display_name: Production Data

