# The url for this app, also used by `dfe_sign_in`
base_url: https://www2.register-trainee-teachers.service.gov.uk

# The url for the google doc feedback link (live version)
feedback_link_url: https://docs.google.com/forms/d/e/1FAIpQLSd6s98QtFceURRhUAguIXutWsJtZRSYehE2o68LvAbchSldiw/viewform

dttp:
  scope: https://dttp.crm4.dynamics.com/.default
  api_base_url: https://dttp.crm4.dynamics.com/api/data/v9.1
  portal_host: traineeteacherportal.education.gov.uk

dfe_sign_in:
  # URL that the users are redirected to for signing in
  issuer: https://oidc.signin.education.gov.uk
  # URL of the users profile
  profile: https://profile.signin.education.gov.uk

dqt:
  base_url: https://teacher-qualifications-api.education.gov.uk/

features:
  sign_in_method: dfe-sign-in
  basic_auth: true
  enable_feedback_link: true
  import_courses_from_ttapi: true
  import_applications_from_apply: true
  publish_course_details: true
  routes:
    early_years_assessment_only: true
    early_years_postgrad: true
    early_years_salaried: true
    early_years_undergrad: true
    opt_in_undergrad: true
    pg_teaching_apprenticeship: true
    provider_led_postgrad: true
    provider_led_undergrad: true
    school_direct_salaried: true
    school_direct_tuition_fee: true
    iqts: true
  google:
    send_data_to_big_query: false
  integrate_with_dqt: false
  hesa_trn_requests: true
  hesa_import:
    sync_collection: true
    sync_trn_data: true
  dqt_import:
    sync_teachers: true
environment:
  name: beta
