name: send-slack-notification
description: Send a Slack notification

inputs:
  slack-title:
    required: true
  slack-message:
    required: true
  slack-webhook:
    required: true
  slack-icon-emoji:
    required: false
    default: ':github-logo:'
  slack-color:
    required: false
    default: '#ef5343'

runs:
  using: composite
  steps:
    - name: Send notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: twd_register_tech
        SLACK_COLOR: ${{ inputs.slack-color }}
        SLACK_ICON_EMOJI: ${{ inputs.slack-icon-emoji }}
        SLACK_USERNAME: Register Trainee Teachers
        SLACK_TITLE: ${{ inputs.slack-title }}
        SLACK_MESSAGE: ${{ inputs.slack-message }}
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
