name: Code Coverage

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
  pull_request:
    types: [opened, reopened, synchronize, labeled]

permissions:
  contents: write
  deployments: write
  packages: write
  pull-requests: write
  id-token: write

jobs:
  build:
    name: Build
    env:
      DOCKER_IMAGE: ghcr.io/dfe-digital/register-trainee-teachers
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOSTNAME: localhost
    outputs:
      docker-image: ${{ steps.build-image.outputs.image }}
      image-tag: ${{ steps.build-image.outputs.tag }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build and push docker image
        id: build-image
        uses: DFE-Digital/github-actions/build-docker-image@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          context: ""

  coverage_tests:
    name: Coverage tests
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build
        uses: ./.github/actions/coverage-tests/
        with:
          docker-image: ${{ needs.build.outputs.docker-image }}
          image-tag: ${{ needs.build.outputs.image-tag }}
          use-next-academic-year: false
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
