name: Code Coverage

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
  pull_request:
    types: [opened, reopened, synchronize, labeled]

permissions:
  contents: write
  deployments: write
  packages: write
  pull-requests: write
  id-token: write

jobs:
  build:
    name: Build
    env:
      DOCKER_IMAGE: ghcr.io/dfe-digital/register-trainee-teachers
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOSTNAME: localhost
    outputs:
      docker-image: ${{ env.DOCKER_IMAGE }}
      image-tag: ${{ env.IMAGE_TAG }}
    runs-on: ubuntu-latest
    environment:
      name: review

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build/
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}

  coverage_tests:
    name: Coverage tests
    needs: [build]

    runs-on: ubuntu-latest
    environment:
      name: review

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/coverage-tests/
        with:
          docker-image: ${{needs.build.outputs.docker-image}}
          image-tag: ${{ needs.build.outputs.image-tag }}
          use-next-academic-year: false
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
