name: Copy database to postgres 13

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
        - qa
        - staging
        - production
        - productiondata
        default: false

jobs:
  backup:
    name: Backup PaaS Database (${{inputs.environment}})
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout

    - name: Setup postgres client
      uses: DFE-Digital/github-actions/install-postgres-client@master

    - name: Set environment variables
      run: |
        tf_vars_file=terraform/workspace-variables/${{inputs.environment}}.tfvars.json
        echo "key_vault_name=$(jq -r '.key_vault_name' ${tf_vars_file})" >> $GITHUB_ENV
        echo "key_vault_infra_secret_name=$(jq -r '.key_vault_infra_secret_name' ${tf_vars_file})" >> $GITHUB_ENV
        echo "paas_space_name=$(jq -r '.paas_space_name' ${tf_vars_file})" >> $GITHUB_ENV

        echo "BACKUP_FILE_NAME=register_${{inputs.environment}}_$(date +"%F")" >> $GITHUB_ENV

    - name: Login to Azure ${{inputs.environment}} environment subscription
      uses: azure/login@v1
      with:
        creds: ${{ secrets[format('AZURE_CREDENTIALS_{0}', inputs.environment)] }}

    - uses: DFE-Digital/keyvault-yaml-secret@v1
      id: get-secrets
      with:
        keyvault: ${{ env.key_vault_name }}
        secret: ${{ env.key_vault_infra_secret_name }}
        key: CF_USER,CF_PASSWORD

    - name: Setup cf cli to ${{ env.paas_space_name }} space
      uses: DFE-Digital/github-actions/setup-cf-cli@master
      with:
        CF_USERNAME:   ${{ steps.get-secrets.outputs.CF_USER }}
        CF_PASSWORD:   ${{ steps.get-secrets.outputs.CF_PASSWORD }}
        CF_SPACE_NAME: ${{ env.paas_space_name }}
        INSTALL_CONDUIT: true

    - name: Backup ${{inputs.environment}} DB
      run: |
        cf conduit register-postgres-${{inputs.environment}} -- pg_dump -E utf8 --clean --if-exists --no-owner --verbose --no-password -f ${BACKUP_FILE_NAME}.sql

    - name: Restore backup to postgres 13
      run: |
        cf conduit register-postgres-13-${{inputs.environment}} -- psql < ${{ env.BACKUP_FILE_NAME }}.sql
