name: Monitor Database logical replication

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"

permissions:
  id-token: write

env:
  SERVICE_NAME: register
  SERVICE_SHORT: rtt
  TF_VARS_PATH: terraform/aks/workspace-variables

jobs:
  monitor-wal-usage:
    name: Parallel postgres monitor
    environment:
      name: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [qa]
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Monitor ${{ matrix.environment }}
      uses: DFE-Digital/github-actions/monitor-postgres-wal@master
      with:
        azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
        azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        environment: ${{ matrix.environment }}
        slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
        app-name: ${{ env.SERVICE_NAME }}-${{ matrix.environment }}
        tf-vars-path: ${{ env.TF_VARS_PATH }}
