name: Disable maintenance

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
        - qa
        - production

jobs:
  disable-maintenance:
    name: Disable maintenance app
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        creds: ${{ secrets[format('AZURE_CREDENTIALS_{0}', github.event.inputs.environment)] }}

    - name: Set ARM and kubelogin environment
      uses: DFE-Digital/github-actions/set-kubelogin-environment@master
      with:
        azure-credentials: ${{ secrets[format('AZURE_CREDENTIALS_{0}', github.event.inputs.environment)] }}

    - name: Disable maintenance app
      run: make ${{ inputs.environment }} disable-maintenance
