name: Restore database from Azure storage

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to restore
        required: true
        default: qa
        type: choice
        options:
        - qa
        - staging
        - sandbox
        - productiondata
        - production
      confirm-production:
        description: Must be set to true if restoring production
        required: true
        default: 'false'
        type: choice
        options:
        - 'false'
        - 'true'
      backup-file:
        description: Name of the backup file in Azure storage. e.g. rtt_prod_2025-01-18.sql.gz. The default value is today's scheduled backup.
        type: string
        required: false

permissions:
  id-token: write

env:
  SERVICE_NAME: register
  SERVICE_SHORT: rtt
  TF_VARS_PATH: terraform/aks/workspace-variables

jobs:
  restore:
    name: Restore AKS Database
    if: ${{ inputs.environment != 'production' || (inputs.environment == 'production' && inputs.confirm-production == 'true' )  }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    concurrency: deploy_${{ inputs.environment }}

    steps:
    - uses: actions/checkout@v4
      name: Checkout

    - name: Set environment variables
      run: |
        source global_config/${{ inputs.environment }}.sh
        tf_vars_file=${{ env.TF_VARS_PATH }}/${{ inputs.environment }}.tfvars.json
        echo "CLUSTER=$(jq -r '.cluster' ${tf_vars_file})" >> $GITHUB_ENV
        echo "NAMESPACE=$(jq -r '.namespace' ${tf_vars_file})" >> $GITHUB_ENV
        echo "RESOURCE_GROUP_NAME=${RESOURCE_NAME_PREFIX}-${SERVICE_SHORT}-${CONFIG_SHORT}-rg" >> $GITHUB_ENV
        echo "STORAGE_ACCOUNT_NAME=${RESOURCE_NAME_PREFIX}${SERVICE_SHORT}dbbkp${CONFIG_SHORT}sa" >> $GITHUB_ENV
        echo "DB_SERVER=${RESOURCE_NAME_PREFIX}-${SERVICE_SHORT}-${CONFIG_SHORT}-pg" >> $GITHUB_ENV
        TODAY=$(date +"%F")
        echo "BACKUP_FILE=${SERVICE_SHORT}_${CONFIG_SHORT}_${TODAY}.sql" >> $GITHUB_ENV
        if [ "${{ inputs.backup-file }}" != "" ]; then
          BACKUP_FILE=${{ inputs.backup-file }}
        else
          BACKUP_FILE=${SERVICE_SHORT}_${CONFIG_SHORT}_${TODAY}.sql.gz
        fi
        echo "BACKUP_FILE=$BACKUP_FILE" >> $GITHUB_ENV

    - name: Restore ${{ inputs.environment }} postgres
      uses: DFE-Digital/github-actions/restore-postgres-backup@master
      with:
        storage-account: ${{ env.STORAGE_ACCOUNT_NAME }}
        resource-group: ${{ env.RESOURCE_GROUP_NAME }}
        app-name: ${{ env.SERVICE_NAME }}-${{ inputs.environment }}
        cluster: ${{ env.CLUSTER }}
        namespace: ${{ env.NAMESPACE }}
        azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
        azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        backup-file: ${{ env.BACKUP_FILE }}
