name: Restore Staging with sanitised data

on:
  workflow_dispatch:

jobs:
  restore_staging:
    name: Restore staging database
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_AKS_TEST }}

    - name: Download Sanitised Backup
      uses: actions/download-artifact@v3
      with:
        name: backup_sanitised

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "v1.26.1" # default is latest stable

    - name: K8 setup
      shell: bash
      run: |
        az aks get-credentials -g s189t01-tsc-ts-rg -n s189t01-tsc-test-aks
        make install-konduit

    - name: Restore backup to aks env database
      shell: bash
      run: |
        bin/konduit.sh -i backup_sanitised.sql -c -t 7200 register-staging -- psql

    - name: Remove PaaS specific event triggers
      shell: bash
      run: |
        bin/konduit.sh register-staging -- psql -c 'drop event trigger forbid_ddl_reader'
        bin/konduit.sh register-staging -- psql -c 'drop event trigger make_readable'
        bin/konduit.sh register-staging -- psql -c 'drop event trigger reassign_owned'
        rm backup_sanitised.sql
