name: Tests workflow

on:
  workflow_call:
    inputs:
      docker-image:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      use-next-academic-year:
        required: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        test-type: [ full-suite ]
        include:
          - test-type: full-suite
            include-pattern: spec/**/*_spec.rb
            exclude-pattern: spec/smoke/*_spec.rb

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Bring docker image up
      uses: ./.github/actions/bring-docker-image-up/
      with:
        azure-credentials: ${{ secrets.AZURE_CREDENTIALS_REVIEW }}
        docker-image: ${{ inputs.docker-image}}
        image-tag: ${{ inputs.image-tag }}

    - name: Setup tests dependencies on images
      shell: bash
      run: |
        docker compose exec -T web /bin/sh -c 'bundle config --local disable_exec_load true'
        docker compose exec -T web /bin/sh -c 'bundle exec rake parallel:setup'
        docker compose exec -T web /bin/sh -c "yarn add jest@29.3.1"
        docker compose exec -T web /bin/sh -c "RAILS_ENV=test bundle exec rails assets:precompile"
        docker compose exec -T web /bin/sh -c 'apk add chromium chromium-chromedriver'

    - name: "${{ inputs.use-next-academic-year && 'Next academic year' || 'Current academic year' }} ${{ matrix.test-type }} tests"
      run: |
        docker compose exec -T web /bin/sh -c 'COVERAGE=true bundle exec --verbose rspec --pattern "${{ env.INCLUDE_PATTERN }}" --exclude-pattern "${{ env.EXCLUDE_PATTERN }}" --bisect'
      env:
        IMAGE_TAG: ${{ env.DOCKER_IMAGE_TAG }}
        INCLUDE_PATTERN: ${{ matrix.include-pattern }}
        EXCLUDE_PATTERN: ${{ matrix.exclude-pattern || ' ' }}
        TEST_MATRIX_NODE_NAME: ${{ matrix.test-type }}
        USE_NEXT_ACADEMIC_YEAR: ${{ inputs.use-next-academic-year }}

    - name: Check for Failure
      uses: ./.github/actions/send-slack-notification/
      if: ${{ failure() && github.ref == 'refs/heads/main' }}
      with:
        slack-title: "${{ inputs.use-next-academic-year && 'Next academic year' || 'Current academic year' }} tests"
        slack-message: "':alert: ${{ inputs.use-next-academic-year &&  'Next academic year' || 'Current academic year'}}  ${{ matrix.test-type }} test failure for ${{ matrix.tests_type  }} on commit ${{env.IMAGE_TAG}} :sadpanda:"
        slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
